version: 2.1
orbs:
  node: circleci/node@5.1.0
executors:
  main_executor:
    machine:
      image: ubuntu-2004:202010-01
jobs:
  build-and-test:
    executor: main_executor
    working_directory: "~/project"
    steps:
      - run:
          name: Use latest version of Node installed via NVM
          command: |
            nvm ls-remote && nvm install 16.20.0 && nvm use 16.20.0 && nvm alias default 16.20.0
      - checkout
      - node/install-packages:
          override-ci-command: "npm ci --force"
      - run:
          name: Build Application
          command: npm run build
      - run:
          name: Run Integration Tests
          command: npm run integration-tests
      - persist_to_workspace:
          root: ~/
          paths:
            - project/server/public
  deploy:
    executor:
      name: main_executor
    working_directory: "~/project"
    steps:
      - attach_workspace:
          at: ~/
      - add_ssh_keys
      - run:
          name: Add Server to SSH Known Hosts
          command: ssh-keyscan $SERVER_URL >> ~/.ssh/known_hosts
      - run:
          name: SCP Static Files to Live Server
          command: cd ~/project/server/public && scp -prv * ${SERVER_LOGIN_URI}:${SERVER_STATIC_FILES_PATH}
workflows:
    build:
      jobs:
        - build-and-test
        - deploy:
            requires:
              - build-and-test
            filters:
              branches:
                only:
                  - master
